// Code generated by protoc-gen-go.
// source: prototweet.proto
// DO NOT EDIT!

/*
Package prototweet is a generated protocol buffer package.

It is generated from these files:
	prototweet.proto

It has these top-level messages:
	Tweet
*/
package prototweet

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Tweet struct {
	Id               *int64            `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	User             *Tweet_User       `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Text             *string           `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	Coordinates      *Tweet_Coordinate `protobuf:"bytes,4,opt,name=coordinates" json:"coordinates,omitempty"`
	Hashtags         []string          `protobuf:"bytes,5,rep,name=hashtags" json:"hashtags,omitempty"`
	Pictures         []*Tweet_Image    `protobuf:"bytes,6,rep,name=pictures" json:"pictures,omitempty"`
	Urls             []*Tweet_Url      `protobuf:"bytes,7,rep,name=urls" json:"urls,omitempty"`
	Mentions         []*Tweet_User     `protobuf:"bytes,8,rep,name=mentions" json:"mentions,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Tweet) Reset()         { *m = Tweet{} }
func (m *Tweet) String() string { return proto.CompactTextString(m) }
func (*Tweet) ProtoMessage()    {}

func (m *Tweet) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Tweet) GetUser() *Tweet_User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Tweet) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

func (m *Tweet) GetCoordinates() *Tweet_Coordinate {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Tweet) GetHashtags() []string {
	if m != nil {
		return m.Hashtags
	}
	return nil
}

func (m *Tweet) GetPictures() []*Tweet_Image {
	if m != nil {
		return m.Pictures
	}
	return nil
}

func (m *Tweet) GetUrls() []*Tweet_Url {
	if m != nil {
		return m.Urls
	}
	return nil
}

func (m *Tweet) GetMentions() []*Tweet_User {
	if m != nil {
		return m.Mentions
	}
	return nil
}

type Tweet_User struct {
	Id               *int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Tweet_User) Reset()         { *m = Tweet_User{} }
func (m *Tweet_User) String() string { return proto.CompactTextString(m) }
func (*Tweet_User) ProtoMessage()    {}

func (m *Tweet_User) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Tweet_User) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Tweet_Image struct {
	Source           *string `protobuf:"bytes,1,opt,name=source,def=TWITTER" json:"source,omitempty"`
	Url              *string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Tweet_Image) Reset()         { *m = Tweet_Image{} }
func (m *Tweet_Image) String() string { return proto.CompactTextString(m) }
func (*Tweet_Image) ProtoMessage()    {}

const Default_Tweet_Image_Source string = "TWITTER"

func (m *Tweet_Image) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return Default_Tweet_Image_Source
}

func (m *Tweet_Image) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

type Tweet_Url struct {
	Display          *string `protobuf:"bytes,1,opt,name=display" json:"display,omitempty"`
	Actual           *string `protobuf:"bytes,2,opt,name=actual" json:"actual,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Tweet_Url) Reset()         { *m = Tweet_Url{} }
func (m *Tweet_Url) String() string { return proto.CompactTextString(m) }
func (*Tweet_Url) ProtoMessage()    {}

func (m *Tweet_Url) GetDisplay() string {
	if m != nil && m.Display != nil {
		return *m.Display
	}
	return ""
}

func (m *Tweet_Url) GetActual() string {
	if m != nil && m.Actual != nil {
		return *m.Actual
	}
	return ""
}

type Tweet_Coordinate struct {
	Latitude         *float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude        *float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Tweet_Coordinate) Reset()         { *m = Tweet_Coordinate{} }
func (m *Tweet_Coordinate) String() string { return proto.CompactTextString(m) }
func (*Tweet_Coordinate) ProtoMessage()    {}

func (m *Tweet_Coordinate) GetLatitude() float64 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *Tweet_Coordinate) GetLongitude() float64 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func init() {
}
